In [83]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [84]:
df =pd.read_csv("insurance.csv")
df

,Age,BMI,Children,Smoker,Region,Exercise_Level,Insurance_Cost
0,50,34.0,0,Yes,West,Medium,19173
1,53,18.7,0,Yes,West,High,17365
2,64,30.0,4,No,West,Medium,24893
3,37,33.7,0,Yes,North,High,19040
4,36,21.1,0,Yes,East,Medium,13092
5,52,27.7,0,No,East,Low,20488
6,60,33.6,3,Yes,West,Medium,24476
7,34,18.6,3,Yes,North,High,15333
8,62,29.9,2,Yes,North,High,23165
9,60,23.1,1,Yes,East,Medium,20941


In [85]:
df=df.drop("Smoker",axis=1)
df=df.drop("Region",axis=1)
df=df.drop("Exercise_Level",axis=1)


In [86]:
df.ndim

2

In [87]:
df.size

240

In [88]:
df.describe()

,Age,BMI,Children,Insurance_Cost
count,60.000000,60.000000,60.000000,60.000000
mean,42.833333,27.101667,1.916667,17784.750000
std,13.360918,5.307669,1.510322,3505.246777
min,18.000000,18.400000,0.000000,9156.000000
25%,33.000000,22.975000,0.750000,15366.750000
50%,42.000000,27.450000,2.000000,17352.500000
75%,54.250000,32.175000,3.000000,19995.000000
max,64.000000,35.000000,4.000000,24893.000000


In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             60 non-null     int64  
 1   BMI             60 non-null     float64
 2   Children        60 non-null     int64  
 3   Insurance_Cost  60 non-null     int64  
dtypes: float64(1), int64(3)
memory usage: 2.0 KB


In [90]:
print("Checking for Missing Values")
print(df.isnull().sum())

Checking for Missing Values
Age               0
BMI               0
Children          0
Insurance_Cost    0
dtype: int64


In [91]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [92]:
X = df.drop("Insurance_Cost", axis=1)   
y = df["Insurance_Cost"]               

In [93]:
mm = MinMaxScaler()
scaled_features = mm.fit_transform(X)

In [94]:
scaled_data = pd.DataFrame(scaled_features, columns=X.columns)
print("MinMax Scaled Data :")
print(scaled_data)

MinMax Scaled Data :
         Age       BMI  Children
0   0.695652  0.939759      0.00
1   0.760870  0.018072      0.00
2   1.000000  0.698795      1.00
3   0.413043  0.921687      0.00
4   0.391304  0.162651      0.00
5   0.739130  0.560241      0.00
6   0.913043  0.915663      0.75
7   0.347826  0.012048      0.75
8   0.956522  0.692771      0.50
9   0.913043  0.283133      0.25
10  0.717391  0.921687      1.00
11  0.173913  0.969880      1.00
12  0.543478  0.945783      1.00
13  0.021739  0.463855      0.50
14  0.173913  0.861446      0.75
15  0.173913  0.843373      0.50
16  0.847826  0.301205      1.00
17  0.347826  0.825301      0.25
18  0.000000  0.012048      0.00
19  0.521739  0.584337      0.75
20  0.913043  0.210843      0.75
21  0.847826  0.096386      0.50
22  0.891304  0.054217      0.75
23  0.521739  0.686747      1.00
24  0.826087  0.325301      1.00
25  0.739130  0.716867      0.50
26  0.043478  0.042169      1.00
27  0.782609  0.301205      0.25
28  0.934783  0.530120

In [95]:
ss=StandardScaler()
scaled_features = ss.fit_transform(X)
scaled_data = pd.DataFrame(scaled_features, columns=X.columns)
print("Standard scaled Data :")
print(scaled_data)

Standard scaled Data :
         Age       BMI  Children
0   0.540917  1.310660 -1.279754
1   0.767347 -1.596288 -1.279754
2   1.597592  0.550673  1.391037
3  -0.440281  1.253661 -1.279754
4  -0.515758 -1.140296 -1.279754
5   0.691870  0.113681 -1.279754
6   1.295685  1.234661  0.723339
7  -0.666712 -1.615288  0.723339
8   1.446638  0.531674  0.055641
9   1.295685 -0.760303 -0.612056
10  0.616394  1.253661  1.391037
11 -1.270526  1.405658  1.391037
12  0.012579  1.329659  1.391037
13 -1.798863 -0.190313  0.055641
14 -1.270526  1.063664  0.723339
15 -1.270526  1.006665  0.055641
16  1.069254 -0.703304  1.391037
17 -0.666712  0.949666 -0.612056
18 -1.874340 -1.615288 -1.279754
19 -0.062897  0.189680  0.723339
20  1.295685 -0.988299  0.723339
21  1.069254 -1.349292  0.055641
22  1.220208 -1.482290  0.723339
23 -0.062897  0.512674  1.391037
24  0.993778 -0.627305  1.391037
25  0.691870  0.607672  0.055641
26 -1.723386 -1.520289  1.391037
27  0.842824 -0.703304 -0.612056
28  1.371161  0.0186

In [96]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.feature_selection import SelectKBest, f_regression

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [98]:
model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [99]:
y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.8508769097395432
RMSE: 1143.4722550540223


In [100]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [101]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [102]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [103]:
y_pred = knn.predict(X_test)
y_test

0     19173
5     20488
36    23334
45    19716
13    12980
54    16064
33    13141
48    16960
12    18850
57    14733
46    17340
50    15639
Name: Insurance_Cost, dtype: int64

In [104]:
print(confusion_matrix(y_test, y_pred))


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [105]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

        9156       0.00      0.00      0.00       0.0
       11959       0.00      0.00      0.00       0.0
       12980       0.00      0.00      0.00       1.0
       13092       0.00      0.00      0.00       0.0
       13141       0.00      0.00      0.00       1.0
       14733       0.00      0.00      0.00       1.0
       14929       0.00      0.00      0.00       0.0
       15639       0.00      0.00      0.00       1.0
       16064       0.00      0.00      0.00       1.0
       16192       0.00      0.00      0.00       0.0
       16275       0.00      0.00      0.00       0.0
       16960       0.00      0.00      0.00       1.0
       17340       0.00      0.00      0.00       1.0
       17909       0.00      0.00      0.00       0.0
       18850       0.00      0.00      0.00       1.0
       18922       0.00      0.00      0.00       0.0
       19173       0.00      0.00      0.00       1.0
       19716       0.00    